### ISSUE TITLE
Problem changing brightness & color

### ISSUE THREAD

**Issue by terrag42** [thehookup/Alexa-Enabled-LED-Clock#3]
I've got the Lazy Grid Clock displaying the correct time, and Alexa has discovered my four Philips Hue devices, but I cannot make any changes to brightness or color. For instance, when I move the brightness slider on the app, the slider stays there for two seconds and then goes back to the previous value, which is 39% for the first device, 5% for the second device, and 49% for the third device.
I've tried using the clock with both a Wemos D1 Mini LITE, and an ESP-201 board with the same result.

**Comment by DutchTaurus** [comment]
I'm experiencing the same thing, am using a NodeMCU V1.0. It could very well be caused by Aircoookie's ESPAlexa library, outside of direct control of Rob. If it is it's weird this code works for Rob. Will test with other examples of the ESPAlexa library when I find the time.

UPDATE:
The problem seems to arise (for others including me) when an Echo Dot V1 or V2 is involved. At the moment this sketch now compiles and fully works for me with ESP8266 compile tools V2.5.2, FastLED library V3.2.9 and espalexa library V2.4.3. Make sure the #define ESPALEXA_ASYNC in this sketch is uncommented.

It does compile with a very old version of the ESP8266 compile tools (V2.3.0) as well without the #define and the latest espalexa library if you so prefer. HTH

**Comment by sb43201** [comment]
Same issue with Wemos D1 R1. But works fine on NodeMCU V0.9 and V1.0. 

However I found the NodeMUC sometimes hanging on ESP.restart()

**Comment by terrag42** [comment]
After running this clock for almost a year with no malfunction, I decided to open the Alexa app and give some of those sliders a tweak. To my surprise, everything worked as intended! I love my new grid clock now. Thanks @thehookup !
